apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xkoka-ambulance-ufe-content
spec:
  microFrontend: xkoka-ambulance-ufe
  element: xkoka-ambulance-wl-app
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xkoka-ambulance-wl(/.*)?$"